version: '3.7'

services:
  onc-db-dev:
    container_name: onc-db-dev
    image: postgres:13
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - type: volume
        source: oncquest_doc_manager_postgres
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    environment:
      - POSTGRES_USER=oncquest_doc_manager_user
      - POSTGRES_PASSWORD=welcome
      - POSTGRES_DB=oncquest_doc_manager

volumes:
  oncquest_doc_manager_postgres:
