# Generated by Django 3.0.5 on 2021-03-19 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=40000)),
                ('score', models.IntegerField()),
                ('edited', models.BooleanField()),
                ('num_replies', models.IntegerField()),
                ('distinguished', models.BooleanField(null=True)),
                ('created_utc', models.DateTimeField(auto_now_add=True, null=True)),
                ('link_id', models.CharField(max_length=15, null=True)),
                ('parent_id', models.CharField(max_length=15, null=True)),
                ('subreddit', models.CharField(max_length=50)),
                ('permalink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('created_utc', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_self', models.BooleanField(null=True)),
                ('score', models.IntegerField()),
                ('edited', models.BooleanField()),
                ('num_replies', models.IntegerField()),
                ('distinguished', models.BooleanField(null=True)),
                ('upvote_ratio', models.FloatField()),
                ('subreddit', models.CharField(max_length=50)),
                ('permalink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker_symbol', models.CharField(max_length=5)),
                ('keywords', models.CharField(max_length=400)),
                ('latest_sentiment', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentimentRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_utc', models.DateTimeField()),
                ('sentiment_rating', models.FloatField(null=True)),
                ('influence_rating', models.FloatField(null=True)),
                ('source_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fetch.Comment')),
                ('source_submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fetch.Submission')),
                ('ticker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fetch.Ticker')),
            ],
        ),
    ]
